CREATE TABLE public.medical_centers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.medical_centers (name, address, phone) VALUES
('City General Hospital', '123 Health St, Medville, 12345', '123-456-7890'),
('Community Clinic', '456 Wellness Ave, Townsville, 54321', '098-765-4321'),
('Downtown Pharmacy', '789 Cure Blvd, Metropolis, 67890', '555-123-4567');
