CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  image_url TEXT,
  tag TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.products (name, price, image_url, tag) VALUES
('Organic Baby Onesie', 24.99, '/placeholder.svg', 'Clothing'),
('Ergonomic Baby Carrier', 129.99, '/placeholder.svg', 'Gear'),
('Natural Diaper Rash Cream', 14.99, '/placeholder.svg', 'Care'),
('Wooden Activity Gym', 89.99, '/placeholder.svg', 'Toys'),
('Silicone Bib Set', 19.99, '/placeholder.svg', 'Feeding'),
('Convertible Crib', 349.99, '/placeholder.svg', 'Nursery');
