// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyovmsdngjmqnhtorzzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55b3Ztc2RuZ2ptcW5odG9yenpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTkzNjksImV4cCI6MjA3MjIzNTM2OX0.jl-VaZbq0XgZ3fh2Xd3FzLnKb2M9F6kCEsoGZug5T-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});